-- Phase 4 — session and calendar layer.
--
-- Windows are stored as TSTZRANGE with GiST exclusion constraints rather than
-- as (start, end) column pairs. Three reasons, in order of weight:
--
--   1. Containment is the query. "Which session is this timestamp in" becomes
--      `span @> ts`, index-backed, instead of a pair of inequalities.
--   2. The exclusion constraint makes overlapping windows for the same session
--      IMPOSSIBLE rather than merely unlikely. A DST bug that emitted two
--      overlapping London sessions would fail at write time instead of
--      silently double-counting at read time.
--   3. It is the modelling technique the architecture doc names as directly
--      transferable — range types and exclusion constraints are how
--      regulatory reporting and reconciliation systems express validity.
--
-- Every span is generated by converting a LOCAL wall-clock time to UTC via
-- its IANA zone. DST then falls out of the conversion instead of being
-- special-cased, which is the only way the US/EU offset weeks come out right
-- without a table of exceptions.

CREATE EXTENSION IF NOT EXISTS btree_gist;

-- --------------------------------------------------------------------------
-- Regional trading sessions.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS session_window (
  session     TEXT      NOT NULL,
  span      TSTZRANGE NOT NULL,
  local_zone  TEXT      NOT NULL,
  CONSTRAINT session_window_no_overlap
    EXCLUDE USING gist (session WITH =, span WITH &&)
);

CREATE INDEX IF NOT EXISTS idx_session_window ON session_window USING gist (span);

-- --------------------------------------------------------------------------
-- The FX trading week: Sunday open to Friday close, both defined at 17:00
-- New York local time so they move with US daylight saving on their own.
--
-- This is what lets Phase 1 tell "market closed" from "feed gap". Dukascopy
-- returns HTTP 200 with a zero-byte body for both, so HTTP status cannot
-- separate them and only this table can.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS market_window (
  span TSTZRANGE NOT NULL,
  CONSTRAINT market_window_no_overlap EXCLUDE USING gist (span WITH &&)
);

CREATE INDEX IF NOT EXISTS idx_market_window ON market_window USING gist (span);

-- --------------------------------------------------------------------------
-- Rollover: the hour after 17:00 New York, when swap is applied and spreads
-- widen structurally.
--
-- Defined in NY local time, which is the fix for the Phase 2 detector's
-- known defect. That detector hardcoded 21:00 UTC and was therefore wrong for
-- the two to three weeks each year when US daylight saving is out of step.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rollover_window (
  span TSTZRANGE NOT NULL,
  CONSTRAINT rollover_window_no_overlap EXCLUDE USING gist (span WITH &&)
);

CREATE INDEX IF NOT EXISTS idx_rollover_window ON rollover_window USING gist (span);

-- --------------------------------------------------------------------------
-- Per-currency holidays.
--
-- A currency holiday means THIN LIQUIDITY, not a closed market. FX trades
-- 24/5 regardless of national holidays; what changes is how many participants
-- are at their desks. The flag this feeds is named `holiday_thin` for exactly
-- that reason — calling it `market_closed` would assert something false.
--
-- A pair has two legs and either can be on holiday. EURUSD on US Independence
-- Day is a different instrument from EURUSD on a normal Thursday, and so is
-- EURUSD on a German holiday.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS currency_holiday (
  currency     TEXT NOT NULL,
  holiday_date DATE NOT NULL,
  name         TEXT NOT NULL,
  PRIMARY KEY (currency, holiday_date)
);

CREATE INDEX IF NOT EXISTS idx_currency_holiday_date ON currency_holiday (holiday_date);
